name: Build

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build
        run: ./gradlew build
      - name: Find built JAR
        id: find-jar
        run: |
          JAR_PATH=$(find target -name '*.jar' | grep -v 'original' | head -n 1)
          echo "JAR_PATH=$JAR_PATH" >> $GITHUB_ENV

      - name: Upload JAR file
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: ${{ env.JAR_PATH }}